name: testscreens
description: Goober Testscreens Flutter application.

dependencies:
  flutter:
    sdk: flutter
    
  font_awesome_flutter: "6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
  uses-material-design: true

  assets:
    - assets/subjects.json
    - images/profile_header_background.png