name: testscreens
description: Goober Testscreens Flutter application.

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: "0.1.0"
  firebase_auth: "0.5.3"
  cloud_firestore: "0.3.0"
  google_sign_in: "3.0.0"
  font_awesome_flutter: "6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
  uses-material-design: true

  assets:
    - assets/subjects.json
    - images/profile_header_background.png